Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.lnsw.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.32
        Port: 7051

  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.co.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.36
        Port: 8051

  - &Org3
    Name: Org3MSP
    ID: Org3MSP
    MSPDir: crypto-config/peerOrganizations/org3.sl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.38
        Port: 9051

  - &Org4
    Name: Org4MSP
    ID: Org4MSP
    MSPDir: crypto-config/peerOrganizations/org4.to.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.39
        Port: 10051

  - &Org5
    Name: Org5MSP
    ID: Org5MSP
    MSPDir: crypto-config/peerOrganizations/org5.inaport.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org5MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.33
        Port: 11051

  - &Org6
    Name: Org6MSP
    ID: Org6MSP
    MSPDir: crypto-config/peerOrganizations/org6.bank.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org6MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
    AnchorPeers:
      - Host: 10.239.54.23
        Port: 12051

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - 10.239.54.32:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
  EtcdRaft:
    Consenters:
      - Host: 10.239.54.32
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      - Host: 10.239.54.36
        Port: 8050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererCo.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererCo.example.com/tls/server.crt
      - Host: 10.239.54.38
        Port: 9050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererSl.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererSl.example.com/tls/server.crt
      - Host: 10.239.54.32
        Port: 13050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererLnsw.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererLnsw.example.com/tls/server.crt
      - Host: 10.239.54.39
        Port: 10050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererTo.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererTo.example.com/tls/server.crt
      - Host: 10.239.54.33
        Port: 11050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererInaport.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererInaport.example.com/tls/server.crt
      - Host: 10.239.54.23
        Port: 12050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererBank.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/ordererBank.example.com/tls/server.crt
  Addresses:
    - 10.239.54.32:7050
    - 10.239.54.36:8050
    - 10.239.54.38:9050
    - 10.239.54.32:13050
    - 10.239.54.39:10050
    - 10.239.54.33:11050
    - 10.239.54.23:12050

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
          - *Org2
          - *Org3
          - *Org4
          - *Org5
          - *Org6

  ChannelProfile:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6