OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
      - Hostname: ordererCo
      - Hostname: ordererSl

PeerOrgs:
  - Name: Org1
    Domain: org1.co.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.sl.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1