OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.co.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.sl.com
    Template:
      Count: 1
    Users:
      Count: 1