OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - orderer.example.com       # DNS
          - 10.239.54.32              # IP Address

PeerOrgs:
  - Name: Org1
    Domain: org1.lnsw.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org1.lnsw.com   # DNS
          - 10.239.54.32          # IP Address
  - Name: Org2
    Domain: org2.co.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org2.co.com   # DNS
          - 10.239.54.36          # IP Address
  - Name: Org3
    Domain: org3.sl.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org3.sl.com   # DNS
          - 10.239.54.38          # IP Address
  - Name: Org4
    Domain: org4.to.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org4.to.com   # DNS
          - 10.239.54.39          # IP Address
  - Name: Org5
    Domain: org5.inaport.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org5.inaport.com   # DNS
          - 10.239.54.33          # IP Address
  - Name: Org6
    Domain: org6.bank.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org6.bank.com   # DNS
          - 10.239.54.23          # IP Address