OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - orderer.example.com       # DNS
          - 10.216.74.134              # IP Address

PeerOrgs:
  - Name: Org1
    Domain: org1.lnsw.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org1.lnsw.com   # DNS
          - 10.216.74.134          # IP Address
  - Name: Org2
    Domain: org2.co.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org2.co.com   # DNS
          - 10.216.74.133          # IP Address