# SPDX-License-Identifier: Apache-2.0
version: "2.1"

volumes:
  pgdata:
    external:
      name: blockchain-insw_pgdata
  walletstore:
    external:
      name: blockchain-insw_walletstore

networks:
  insw-network:
    external: true

services:
  explorer.example.com:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=explorerdb.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=8086
    volumes:
      - ${EXPLORER_CONFIG_FILE_PATH}:/opt/explorer/app/platform/fabric/config.json
      - ${EXPLORER_PROFILE_DIR_PATH}:/opt/explorer/app/platform/fabric/connection-profile
      - ${FABRIC_CRYPTO_PATH}:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8086:8086
    networks:
      - insw-network
