# SPDX-License-Identifier: Apache-2.0
version: "2.1"

volumes:
  pgdata:
    external:
      name: blockchain-insw_pgdata
  walletstore:
    external:
      name: blockchain-insw_walletstore

networks:
  insw-network:
    external: true

services:
  explorerdb.example.com:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb.example.com
    hostname: explorerdb.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - insw-network

  explorer.example.com:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=10.239.54.32
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=8080
    volumes:
      - ${EXPLORER_CONFIG_FILE_PATH}:/opt/explorer/app/platform/fabric/config.json
      - ${EXPLORER_PROFILE_DIR_PATH}:/opt/explorer/app/platform/fabric/connection-profile
      - ${FABRIC_CRYPTO_PATH}:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.example.com:
        condition: service_healthy
    networks:
      - insw-network
