# SPDX-License-Identifier: Apache-2.0
version: "2.1"

volumes:
  pgdata:
  walletstore:

networks:
  insw-network:
    external: true

services:
  explorerdb.example.com:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb.example.com
    hostname: explorerdb.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRESQL_SSL_ENABLED=true # Add this line
      - POSTGRESQL_SSL_KEY=/var/lib/postgresql/server.key # Add this line
      - POSTGRESQL_SSL_CERT=/var/lib/postgresql/server.crt # Add this line
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ssl-certs/server.key:/var/lib/postgresql/server.key # Add this line
      - ./ssl-certs/server.crt:/var/lib/postgresql/server.crt # Add this line
    networks:
      - insw-network

  explorer.example.com:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=explorerdb.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DATABASE_PORT=5432
      - EXPLORER_CONFIG_FILE_PATH=/opt/explorer/app/platform/fabric/config.json
      - EXPLORER_PROFILE_DIR_PATH=/opt/explorer/app/platform/fabric/connection-profile
      - EXPLORER_SYNC_BLOCKSYNCTIME_MIN=10
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - SSL_ENABLED=true  # Add this line
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - walletstore:/opt/wallet
      - ./ssl-certs:/opt/explorer/app/ssl-certs # Add this line
    ports:
      - 8080:8080
    depends_on:
      explorerdb.example.com:
        condition: service_healthy
    networks:
      - insw-network
