# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  pgdata:
  walletstore:

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.co.com:
    container_name: peer0.org1.co.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.co.com
      - CORE_PEER_ADDRESS=peer0.org1.co.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.co.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.co.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.co.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.co.com/peers/peer0.org1.co.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.co.com/peers/peer0.org1.co.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.co.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.org2.sl.com:
    container_name: peer0.org2.sl.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.sl.com
      - CORE_PEER_ADDRESS=peer0.org2.sl.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.sl.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.sl.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.co.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.sl.com/peers/peer0.org2.sl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.sl.com/peers/peer0.org2.sl.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.sl.com:/var/hyperledger/production
    ports:
      - 9051:9051

